services:
  djangoservice:
    build: .
    container_name: django-container1
    volumes:
      -  .:/aaaproject6
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postdatabase_name
      - POSTGRES_USER=postdatabase_user
      - POSTGRES_PASSWORD=postdatabase_password
      - DB_HOST=postdatabaseservice
      - DB_PORT=5432
    depends_on:
      postdatabaseservice:
        condition: service_healthy



  postdatabaseservice:
    image: postgres:13
    container_name: postdatabase-container
    environment:
      POSTGRES_USER: postdatabase_user
      POSTGRES_PASSWORD: postdatabase_password
      POSTGRES_DB: postdatabase_name
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postdatabase_user", "-d", "postdatabase_name"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    name: django_database_network